#dist: buster

language: python
python:
  #- 3.6
  - 3.7
  - 3.8
  - 3.9
  #- pypy3.7

addons:
  apt:
    packages:
      - poppler-utils

before_install:
  - sudo apt-get install -y poppler-utils
  - python -m pip install --upgrade pip

install:
  - pip install codecov
  - pip install tox
  - pip install tox-travis
script:
  - coverage --version
  - tox

after_success:
  - coverage report -m
